### ISSUE TITLE
Vitest failing with "Error: require() of ES Module" with @babel/runtime/helpers/esm/slicedToArray.js 

### ISSUE THREAD

**Issue by cassmtnr** [alex-vukov/module-federation-import-remote#11]
Hey, I am doing a migration from our CRA application that uses Jest to Vitest and when I am running any test that uses the module-federation-import-remote I get this error thrown:

```
Error: require() of ES Module /path-to-app/node_modules/@babel/runtime/helpers/esm/slicedToArray.js from /path-to-app/node_modules/module-federation-import-remote/dist/cjs/index.js not supported.
Instead change the require of slicedToArray.js in /path-to-app/node_modules/module-federation-import-remote/dist/cjs/index.js to a dynamic import() which is available in all CommonJS modules.
 ❯ Object.<anonymous> node_modules/module-federation-import-remote/dist/cjs/index.js:5:22
 ❯ async /path-to-app/src/hooks/useMountMicroFrontend/useMountMicroFrontend.ts:1:31
 ❯ async /path-to-app/src/hooks/index.ts:22:183
 ❯ async /path-to-app/src/features/login/pages/Maintenance/Maintenance.tsx:7:31
 ❯ async /path-to-app/src/RenderApp.tsx:3:31
 ❯ async /path-to-app/src/RenderApp.test.tsx:6:23
 ```
 
Does anyone know a way to avoid that?
I saw this issue in Vitest but it didn't solve the issue: https://github.com/vitest-dev/vitest/issues/2742

And just installing @babel/runtime doesn't solve it as well.

**Comment by alex-vukov** [comment]
Hi! Do you have some way to reproduce the issue? Maybe a snippet of code or a test repo?

**Comment by alex-vukov** [comment]
Ignore my previous response. I think I see the problem. I will make a fix tomorrow morning and I will update you when it's released so you can test.

**Comment by alex-vukov** [comment]
I have released the fix. Please update module-federation-import-remote to the latest available version. I am now closing the issue. Thank you very much for reporting it!
