### ISSUE TITLE
Unable to load remote module with importRemote function

### ISSUE THREAD

**Issue by ps185453** [alex-vukov/module-federation-import-remote#16]
Hi Team, 

 I have MFE application where I am trying to load external module with `importRemote` function, but I am getting error, please check this issue and guide me what I am missing here.

Invoking function with input data

importRemote({
       url: http://localhost:4004,
       scope: "myExternalApp",
       module: "SampleApp",
       remoteEntryFileName: "remoteEntry.js"
}); 

Here is the error I am getting

<img width="706" alt="Screenshot 2023-10-27 at 3 28 19 PM" src="https://github.com/alex-vukov/module-federation-import-remote/assets/143381986/1c92f1c7-95a9-4e9d-ac28-18b2eec1405a">

**Comment by alex-vukov** [comment]
Hi,
It seems that your remote entry is not being served. A simple check is that you should be able to see http://localhost:4004/remoteEntry.js in your web browser in order to be able to load the remote.
