### ISSUE TITLE
Can not load modules after build - NextJS

### ISSUE THREAD

**Issue by haghsheno** [alex-vukov/module-federation-import-remote#17]
Hey, I am using module federation in two NextJS app.
In dev mode both apps work fine and can load each other remote modules. But after build and start them, loading module throws and error that says "Remote loaded successfully but remoteProject could not be found! Verify that the name is correct in the Webpack configuration!"

This is on of my configuration in host for importing module:
``` js
  importRemote({
    url: "http://localhost:5001/_next/static/chunks",
    scope: "remoteProject",
    module: "remoteText",
  })
```

Should i change anything for build time?
also i'm using typscript.
NextJS Version: 13.1.6

**Comment by haghsheno** [comment]
I've update to @module-federation/nextjs-mf: "8.0.1-4" and it got fixed.

**Comment by alex-vukov** [comment]
I am sorry for the delay in my response. This library will not work with Next as you already figured out. It is only for client side use. I will update the documentation to address this.
