### ISSUE TITLE
Not working in production build

### ISSUE THREAD

**Issue by jarecsni** [alex-vukov/module-federation-import-remote#22]
When I run my application's production build, and the host application is trying to import remote modules, I get the following error:

TypeError: n.l is not a function

This is coming from the loadRemote() function:

<img width="351" alt="image" src="https://github.com/user-attachments/assets/30313c27-4f6b-4578-a2f0-8c7930941319">

It seems that '.l' whatever it is, is not available on the __webpack_require__ object.

Worth mentioning that this works fine in development mode.

**Comment by alex-vukov** [comment]
It seems that the internal __webpack_require__ variable is not recognized as such an is renamed by your production build. Can you tell me how to reproduce the issue?

**Comment by jarecsni** [comment]
Thanks for the prompt reply! So the application I'm working on is available publicly: https://github.com/jarecsni/composaic-demo

If you check out and install the project, you can run the host in production mode in the main project folder (npm run build, npm run serve); the remote is in a subfolder called test-apps/plugin-template (need to npm i there too, then npm run start). The plugin project can be run both in dev or prod mode, it doesn't matter for this issue. If you want to see things working, you can run the host in dev mode (npm run start).

Hope this helps reproduce the issue, and thanks for looking into this.

**Comment by alex-vukov** [comment]
Thank you! I was able to reproduce the issue and it comes from the fact that in the ModuleFederationPlugin settings you use `eager: true` in the `react` and `composaic` dependencies. This triggers the request to load the remoteEntry file earlier than the `__webpack_require__.l` function is created. I was planning to remove the dependency on this internal Webpack function anyway so I will release a new version of the package which doesn't use it. I will close this issue when it is released.

**Comment by jarecsni** [comment]
Thanks for looking into this Alex! I still find it interesting that this is only surfaces in production builds (the ```eager: true``` is set for both dev and prod builds).

**Comment by alex-vukov** [comment]
It's strange but it seems Webpack bootstraps in a different way when it's started in development mode. I have released a new version `1.1.0` which no longer depends on `__webpack_require__.l` and I am closing the issue
